// Generates data/flags.ts by extracting the dominant palette of every flag on
// flagcdn.com. Run with: npm run gen:flags
//
// For each 2-letter ISO country/territory code we download the flag PNG, bucket
// its pixels by colour, and keep the few most-dominant, visually-distinct bands.
import { PNG } from "pngjs";
import { writeFileSync } from "node:fs";

const CODES_URL = "https://flagcdn.com/en/codes.json";
const flagPng = (iso) => `https://flagcdn.com/w160/${iso}.png`;

const EXCLUDE = new Set(["eu", "un"]); // not countries
const CONCURRENCY = 16;
const QUANT = 16; // colour quantisation step (reduces anti-alias noise)
const MIN_SHARE = 0.05; // a band must cover >=5% of pixels (after the 1st)
const DISTINCT = 60; // min RGB distance to count as a separate colour
const MAX_COLORS = 4;

const rgbDist = (a, b) =>
  Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);

const toHex = ([r, g, b]) =>
  "#" +
  [r, g, b]
    .map((n) => Math.max(0, Math.min(255, n)).toString(16).padStart(2, "0"))
    .join("")
    .toUpperCase();

async function extractColors(iso) {
  const res = await fetch(flagPng(iso));
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const png = PNG.sync.read(Buffer.from(await res.arrayBuffer()));
  const { data } = png;

  const buckets = new Map();
  let total = 0;
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] < 128) continue; // skip transparent
    const r = data[i],
      g = data[i + 1],
      b = data[i + 2];
    const key = `${Math.round(r / QUANT)},${Math.round(g / QUANT)},${Math.round(b / QUANT)}`;
    let e = buckets.get(key);
    if (!e) buckets.set(key, (e = { count: 0, r: 0, g: 0, b: 0 }));
    e.count++;
    e.r += r;
    e.g += g;
    e.b += b;
    total++;
  }
  if (!total) return [];

  const sorted = [...buckets.values()]
    .sort((x, y) => y.count - x.count)
    .map((e) => ({
      rgb: [Math.round(e.r / e.count), Math.round(e.g / e.count), Math.round(e.b / e.count)],
      share: e.count / total,
    }));

  const picked = [];
  for (const c of sorted) {
    if (picked.length >= MAX_COLORS) break;
    if (picked.length > 0 && c.share < MIN_SHARE) continue;
    if (picked.every((p) => rgbDist(p.rgb, c.rgb) > DISTINCT)) picked.push(c);
  }
  return picked.map((p) => toHex(p.rgb));
}

async function pool(items, n, fn) {
  const out = new Array(items.length);
  let idx = 0;
  const worker = async () => {
    while (idx < items.length) {
      const i = idx++;
      try {
        out[i] = await fn(items[i]);
      } catch (e) {
        out[i] = null;
        console.error("  skip", items[i][0], e.message);
      }
    }
  };
  await Promise.all(Array.from({ length: n }, worker));
  return out;
}

const codes = await (await fetch(CODES_URL)).json();
const entries = Object.entries(codes).filter(
  ([iso]) => /^[a-z]{2}$/.test(iso) && !EXCLUDE.has(iso),
);
console.log(`fetching ${entries.length} flags @ concurrency ${CONCURRENCY}...`);

const results = await pool(entries, CONCURRENCY, async ([iso, name]) => ({
  country: name,
  iso,
  colors: await extractColors(iso),
}));

const flags = results
  .filter((f) => f && f.colors.length > 0)
  .sort((a, b) => a.country.localeCompare(b.country));

const body = flags
  .map(
    (f) =>
      `  { country: ${JSON.stringify(f.country)}, iso: ${JSON.stringify(f.iso)}, colors: [${f.colors
        .map((c) => JSON.stringify(c))
        .join(", ")}] },`,
  )
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-flags.mjs — do not edit by hand.
// Dominant palette colours extracted from flagcdn.com flag images.
export type FlagEntry = { country: string; iso: string; colors: string[] };

export const FLAGS: FlagEntry[] = [
${body}
];
`;

writeFileSync(new URL("../data/flags.ts", import.meta.url), out);
console.log(`wrote data/flags.ts with ${flags.length} flags`);
